spring:
  application:
    name: jwt
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: password
    schema: ssoapp
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.default_schema: ssoapp
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090
jwt:
  secret: "Ptokenhanimy32characterultrasecureandultralongsecret"

crypto:
  salt: "Thats my Kung Fu"
